//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLayer.Personeli
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee : Person
    {
        public int PersonID { get; set; }
        public Nullable<int> DepartamentID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public string Institution { get; set; }
        public string STATUS { get; set; }
    }
}
